// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SatchmobileDemo
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int loading = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int shine = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int catalogList = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int cmdFeatured = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int cmdRecent = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int cmdSearch = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int featuredContainer = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int parentContainer = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int productListElipse = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int productListImage = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int productListName = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int productListPriceRange = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int productListRating = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int title = 2131099651;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Catalog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProductList = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int store_url = 2130968578;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_Default = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
