// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SatchmobileDemo
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int loading = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int shine = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int catalogList = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int cmdFeatured = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int cmdRecent = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int cmdSearch = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int featuredContainer = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int parentContainer = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int productListImage = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int productListName = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int productListPriceRange = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int productListRating = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int searchContainer = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int searchResultList = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int title = 2131165187;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Catalog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProductList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SearchResults = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int search_hint = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int search_label = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int store_url = 2131034114;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_Default = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			private Xml()
			{
			}
		}
	}
}
